/*
 * Copyright (c) 2025–2026 Paul Viandier
 * All rights reserved.
 *
 * This source code is proprietary.
 * Commercial use, redistribution, or modification is strictly prohibited
 * without prior written permission.
 *
 * See the LICENSE file in the project root for full license terms.
 */

import { QuizQuestionMeta } from '../quiz-data';

export const easyQuestions: QuizQuestionMeta[] = [
    { id: 'easy-1', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-2', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-3', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-4', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-5', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-6', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-7', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-8', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-9', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-10', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-11', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-12', type: 'true-false', correctAnswer: 1 },
    { id: 'easy-13', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-14', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-15', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-16', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-17', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-18', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-19', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-20', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-21', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-22', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-23', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-24', type: 'true-false', correctAnswer: 1 },
    { id: 'easy-25', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-26', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-27', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-28', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-29', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-30', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-31', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-32', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-33', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-34', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-35', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-36', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-37', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-38', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-39', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-40', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-41', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-42', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-43', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-44', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-45', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-46', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-47', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-48', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-49', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-50', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-51', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-52', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-53', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-54', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-55', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-56', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-57', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-58', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-59', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-60', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-61', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-62', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-63', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-64', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-65', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-66', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-67', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-68', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-69', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-70', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-71', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-72', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-73', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-74', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-75', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-76', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-77', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-78', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-79', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-80', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-81', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-82', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-83', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-84', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-85', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-86', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-87', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-88', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-89', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-90', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-91', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-92', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-93', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-94', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-95', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-96', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-97', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-98', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'easy-99', type: 'true-false', correctAnswer: 0 },
    { id: 'easy-100', type: 'qcm', correctAnswer: 0, optionCount: 4 }
];
