/*
 * Copyright (c) 2025–2026 Paul Viandier
 * All rights reserved.
 *
 * This source code is proprietary.
 * Commercial use, redistribution, or modification is strictly prohibited
 * without prior written permission.
 *
 * See the LICENSE file in the project root for full license terms.
 */

import { QuizQuestionMeta } from '../quiz-data';

export const mediumQuestions: QuizQuestionMeta[] = [
    { id: 'medium-1', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-2', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-3', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-4', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-5', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-6', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-7', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-8', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-9', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-10', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-11', type: 'true-false', correctAnswer: 1 },
    { id: 'medium-12', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-13', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-14', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-15', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-16', type: 'true-false', correctAnswer: 1 },
    { id: 'medium-17', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-18', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-19', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-20', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-21', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-22', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-23', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-24', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-25', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-26', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-27', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-28', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-29', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-30', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-31', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-32', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-33', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-34', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-35', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-36', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-37', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-38', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-39', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-40', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-41', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-42', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-43', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-44', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-45', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-46', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-47', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-48', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-49', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-50', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-51', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-52', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-53', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-54', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-55', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-56', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-57', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-58', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-59', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-60', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-61', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-62', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-63', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-64', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-65', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-66', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-67', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-68', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-69', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-70', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-71', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-72', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-73', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-74', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-75', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-76', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-77', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-78', type: 'qcm', correctAnswer: 0, optionCount: 4 },
    { id: 'medium-79', type: 'true-false', correctAnswer: 0 },
    { id: 'medium-80', type: 'qcm', correctAnswer: 0, optionCount: 4 }
];
